import { ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useEffect } from 'react';
import PageLayout from '@/components/PageLayout';

const PrivacyPolicy = () => {
  // Scroll to top on mount
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <PageLayout>
      <section className="pt-24 pb-16 px-4 sm:px-6 lg:px-8">
        <Link
          to="/"
          className="inline-flex items-center text-gray-500 hover:text-gray-700 mb-6 transition-colors"
        >
          <ArrowLeft className="mr-2 h-4 w-4" />
          Back to Home
        </Link>

        <h1 className="text-4xl font-bold mb-8">Privacy Policy</h1>

        <div className="prose prose-lg max-w-none">
          <p className="text-gray-600 mb-6">Last updated: June 06, 2024</p>

          <p className="text-gray-600 mb-6">
            This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You
            use the Service and tells You about Your privacy rights and how the law protects You.
          </p>

          <p className="text-gray-600 mb-6">
            We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of
            information in accordance with this Privacy Policy.
          </p>

          <h2>Interpretation and Definitions</h2>
          <h3>Interpretation</h3>
          <p>
            The words of which the initial letter is capitalized have meanings defined under the following conditions. The following
            definitions shall have the same meaning regardless of whether they appear in singular or in plural.
          </p>

          <h3>Definitions</h3>
          <ul>
            <li>
              <strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.
            </li>
            <li>
              <strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where
              "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election
              of directors or other managing authority.
            </li>
            <li>
              <strong>Company</strong> ("the Company", "We", "Us" or "Our") refers to IT Carolina, Charlotte city, North Carolina (USA).
            </li>
            <li>
              <strong>Cookies</strong> are small files that are placed on Your device by a website to store browsing information.
            </li>
            <li>
              <strong>Country</strong> refers to North Carolina, United States.
            </li>
            <li>
              <strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.
            </li>
            <li>
              <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
            </li>
            <li>
              <strong>Service</strong> refers to the Website.
            </li>
            <li>
              <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.
            </li>
            <li>
              <strong>Usage Data</strong> refers to data collected automatically, generated by the use of the Service or its
              infrastructure.
            </li>
            <li>
              <strong>Website</strong> refers to IT Carolina, accessible from{' '}
              <a href="https://www.itcarolina.us" target="_blank" rel="noopener noreferrer">
                https://www.itcarolina.us
              </a>.
            </li>
            <li>
              <strong>You</strong> means the individual accessing or using the Service, or the entity on behalf of which such individual
              is accessing or using the Service.
            </li>
          </ul>

          {/* Add remaining sections here, following the same JSX structure */}
        </div>
      </section>
    </PageLayout>
  );
};

export default PrivacyPolicy;
